#!/bin/bash  
echo "Hello World!"
read -p "Press [Enter] key to continue..."
read -p "1"
read -p "2"
read -p "3"
read -p "4"
#echo "This is a shell script"  
#ls -lah  
#echo "I am done running ls"  
#SOMEVAR='text stuff'  
#echo "$SOMEVAR"



#make sure first line is that
#additional notes:
chmod +x file
