document.addEventListener('DOMContentLoaded',function(event){var yasrRaterInDom=document.getElementsByClassName('yasr-rater-stars');if(yasrRaterInDom.length>0){yasrSetRatingOnLoad(yasrRaterInDom);}
var yasrRaterVVInDom=document.getElementsByClassName('yasr-rater-stars-visitor-votes');if(yasrRaterVVInDom.length>0){yasrVisitorVotesFront(yasrRaterVVInDom);}
var yasrMultiSetVisitorInDom=document.getElementsByClassName('yasr-multiset-visitors-rater');if(yasrMultiSetVisitorInDom.length>0){yasrRaterVisitorsMultiSet(yasrMultiSetVisitorInDom)}
if(yasrRaterVVInDom){if(yasrCommonData.visitorStatsEnabled==='yes'){var yasrStatsInDom=document.getElementsByClassName('yasr-dashicons-visitor-stats');if(yasrStatsInDom){yasrDrawTipsProgress(yasrStatsInDom);}}}
if(typeof yasrMostHighestRanking!=='undefined'){document.getElementById('yasr-highest-rated-posts').style.display='none';}});function yasrShowHighest(){document.getElementById('yasr-most-rated-posts').style.display='none';document.getElementById('yasr-highest-rated-posts').style.display='';}
function yasrShowMost(){document.getElementById('yasr-highest-rated-posts').style.display='none';document.getElementById('yasr-most-rated-posts').style.display='';}
function yasrDrawTipsProgress(yasrStatsInDom){var htmlIdChecked=false;for(var i=0;i<yasrStatsInDom.length;i++){(function(i){var htmlId='#'+yasrStatsInDom.item(i).id;var postId=yasrStatsInDom.item(i).getAttribute('data-postid');var data={action:'yasr_stats_visitors_votes',post_id:postId};var initialContent='<span style="color: #0a0a0a">Loading...</span>';tippy(htmlId,{content:initialContent,theme:'yasr',arrow:'true',arrowType:'round',onShow:function onShow(tip){if(htmlId!==htmlIdChecked){jQuery.post(yasrCommonData.ajaxurl,data,function(response){response=JSON.parse(response);tip.setContent(response);});}},onHidden:function onHidden(){htmlIdChecked=htmlId;}});})(i);}}
function yasrSetRaterValue(starSize,htmlId){starSize=parseInt(starSize);raterJs({starSize:starSize,step:0.1,showToolTip:false,readOnly:true,element:document.getElementById(htmlId),});}
function yasrSetRatingOnLoad(yasrRatingsInDom){for(var i=0;i<yasrRatingsInDom.length;i++){var htmlId=yasrRatingsInDom.item(i).id;var starSize=yasrRatingsInDom.item(i).getAttribute('data-rater-starsize');yasrSetRaterValue(starSize,htmlId);}}
function yasrVisitorVotesFront(yasrRaterVVInDom){for(var i=0;i<yasrRaterVVInDom.length;i++){(function(i){var postId=yasrRaterVVInDom.item(i).getAttribute('data-rater-postid');var htmlId=yasrRaterVVInDom.item(i).id;var uniqueId=htmlId.replace('yasr-visitor-votes-rater-','');var starSize=parseInt(yasrRaterVVInDom.item(i).getAttribute('data-rater-starsize'));var readonly=yasrRaterVVInDom.item(i).getAttribute('data-rater-readonly');var nonce=yasrRaterVVInDom.item(i).getAttribute('data-rater-nonce');var isSingular=yasrRaterVVInDom.item(i).getAttribute('data-issingular');readonly=yasrTrueFalseStringConvertion(readonly);isSingular=yasrTrueFalseStringConvertion(isSingular);raterJs({starSize:starSize,step:1,showToolTip:false,readOnly:readonly,element:document.getElementById(htmlId),rateCallback:function rateCallback(rating,done){document.getElementById('yasr-visitor-votes-container-after-stars-'+uniqueId).innerHTML=yasrCommonData.loaderHtml;rating=rating.toFixed(1);rating=parseFloat(rating);var data={action:'yasr_send_visitor_rating',rating:rating,post_id:postId,nonce_visitor:nonce,is_singular:isSingular};this.setRating(rating);this.disable();jQuery.post(yasrCommonData.ajaxurl,data,function(response){response=JSON.parse(response);document.getElementById('yasr-visitor-votes-container-after-stars-'+uniqueId).innerHTML=response;});done();}});})(i);}}
function yasrRaterVisitorsMultiSet(yasrMultiSetVisitorInDom){var ratingObject="";var ratingArray=[];for(var i=0;i<yasrMultiSetVisitorInDom.length;i++){(function(i){var htmlId=yasrMultiSetVisitorInDom.item(i).id;var readonly=yasrMultiSetVisitorInDom.item(i).getAttribute('data-rater-readonly');readonly=yasrTrueFalseStringConvertion(readonly);var elem=document.querySelector("#"+htmlId);raterJs({starSize:16,step:1,showToolTip:false,readOnly:readonly,element:elem,rateCallback:function rateCallback(rating,done){var postId=elem.getAttribute('data-rater-postid');var setId=elem.getAttribute('data-rater-setid');var setIdField=elem.getAttribute('data-rater-set-field-id');rating=rating.toFixed(1);var vote=parseInt(rating);this.setRating(vote);ratingObject={postid:postId,setid:setId,field:setIdField,rating:vote};ratingArray.push(ratingObject);done();}});})(i);}
jQuery('.yasr-send-visitor-multiset').on('click',function(){var multiSetPostId=this.getAttribute('data-postid');var multiSetId=this.getAttribute('data-setid');jQuery('#yasr-send-visitor-multiset-'+multiSetPostId+'-'+multiSetId).hide();jQuery('#yasr-loader-multiset-visitor-'+multiSetPostId+'-'+multiSetId).show();var data={action:'yasr_visitor_multiset_field_vote',nonce:yasrMultiSetData.nonceVisitor,post_id:multiSetPostId,rating:ratingArray,set_type:multiSetId};jQuery.post(yasrCommonData.ajaxurl,data,function(response){jQuery('#yasr-loader-multiset-visitor-'+multiSetPostId+'-'+multiSetId).text(response);});});}
function yasrTrueFalseStringConvertion(string){if(typeof string==='undefined'||string===null||string===''){string=true;}
if(string==='true'||string==='1'){string=true;}
if(string==='false'||string==='0'){string=false;}
return string;}